YarnShop.WebApp/Controllers/ColorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using YarnShop.WebApp.Models;

namespace YarnShop.WebApp.Controllers
{
    public class ColorsController : Controller
    {
        public IConfiguration Configuration;
        private readonly ILogger _logger;

        public ColorsController(IConfiguration configuration, ILogger<ColorsController> logger)
        {
            Configuration = configuration;
            _logger = logger;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string ControllerName()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();
                List<ColorVM> colorList = new List<ColorVM>();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_restpath))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        colorList = JsonConvert.DeserializeObject<List<ColorVM>>(apiResponse);
                    }
                }

                return View(colorList);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(ex);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();

                ColorVM c = new ColorVM();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        c = JsonConvert.DeserializeObject<ColorVM>(apiResponse);
                    }
                }

                return View(c);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(ex);
            }            
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ColorVM c)
        {
            string _restpath = GetHostUrl().Content + ControllerName();
            ColorVM colorResult = new ColorVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(c);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{c.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        colorResult = JsonConvert.DeserializeObject<ColorVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }
            

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();

                ColorVM c = new ColorVM();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        c = JsonConvert.DeserializeObject<ColorVM>(apiResponse);
                    }
                }

                return View(c);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }            
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ColorVM c)
        {
            string _restpath = GetHostUrl().Content + ControllerName();

            ColorVM cResult = new ColorVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(c);

                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{c.Id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        cResult = JsonConvert.DeserializeObject<ColorVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ColorVM c)
        {
            string _restpath = GetHostUrl().Content + ControllerName();

            ColorVM cResult = new ColorVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(c);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        cResult = JsonConvert.DeserializeObject<ColorVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

YarnShop.WebApp/Controllers/KitsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using YarnShop.WebApp.Models;

namespace YarnShop.WebApp.Controllers
{
    public class KitsController : Controller
    {
        public IConfiguration Configuration;
        private readonly ILogger _logger;

        public KitsController(IConfiguration configuration, ILogger<KitsController> logger)
        {
            Configuration = configuration;
            _logger = logger;
        }

        public ContentResult GetHostUrl()
        {
            var result = Configuration["RestApiUrl:HostUrl"];
            return Content(result);
        }

        private string ControllerName()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();
                List<KitVM> kitList = new List<KitVM>();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_restpath))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        kitList = JsonConvert.DeserializeObject<List<KitVM>>(apiResponse);
                    }
                }

                return View(kitList);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();

                KitVM k = new KitVM();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        k = JsonConvert.DeserializeObject<KitVM>(apiResponse);
                    }
                }
                return View(k);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }  
        }

        [HttpPost]
        public async Task<IActionResult> Edit(KitVM k)
        {
            string _restpath = GetHostUrl().Content + ControllerName();
            KitVM kitResult = new KitVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(k);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PutAsync($"{_restpath}/{k.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        kitResult = JsonConvert.DeserializeObject<KitVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                string _restpath = GetHostUrl().Content + ControllerName();

                KitVM k = new KitVM();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        k = JsonConvert.DeserializeObject<KitVM>(apiResponse);
                    }
                }

                return View(k);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return View(ex);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(KitVM k)
        {
            string _restpath = GetHostUrl().Content + ControllerName();

            KitVM kResult = new KitVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(k);

                    using (var response = await httpClient.DeleteAsync($"{_restpath}/{k.Id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        kResult = JsonConvert.DeserializeObject<KitVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(KitVM k)
        {
            string _yarnTypeRestpath = GetHostUrl().Content + "YarnTypes";

            try
            {
                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync($"{_yarnTypeRestpath}/{k.yarnType.Id}"))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        YarnTypeVM yarnType = JsonConvert.DeserializeObject<YarnTypeVM>(apiResponse);
                        k.yarnType.Color = yarnType.Color;
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }

            string _restpath = GetHostUrl().Content + ControllerName();

            KitVM kResult = new KitVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    string jsonString = System.Text.Json.JsonSerializer.Serialize(k);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        kResult = JsonConvert.DeserializeObject<KitVM>(apiResponse);
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> YarnTypesList()
        {
            try
            {
                string _restpath = GetHostUrl().Content + "YarnTypes";
                List<YarnTypeVM> yarnTypeList = new List<YarnTypeVM>();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_restpath))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        yarnTypeList = JsonConvert.DeserializeObject<List<YarnTypeVM>>(apiResponse);
                    }
                }

                return View(yarnTypeList);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }
        }

        public async Task<IActionResult> KnittingNeedlesList()
        {
            try
            {
                string _restpath = GetHostUrl().Content + "KnittingNeedles";
                List<KnittingNeedleVM> knittingNeedlesList = new List<KnittingNeedleVM>();

                using (var httpClient = new HttpClient())
                {
                    using (var response = await httpClient.GetAsync(_restpath))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        knittingNeedlesList = JsonConvert.DeserializeObject<List<KnittingNeedleVM>>(apiResponse);
                    }
                }
                return View(knittingNeedlesList);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(e);
            }
        }
    }
}

YarnShop.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YarnShop.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">YarnShop.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Start</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Info</a>
                        </li>      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kits" asp-action="Index">Kits</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="YarnBundles" asp-action="Index">Yarn Bundles</a>
                        </li>                  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="YarnTypes" asp-action="Index">Yarn Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KnittingNeedles" asp-action="Index">KnittingNeedles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colors" asp-action="Index">Colors</a>
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Zarejestruj się</a>*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign up</a>
                        </li>

                         @* Admin dla roli "admin" *@
                        @{
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">*Admin panel</a>
                                </li>
                            }
                            else  //tylko wyswietl nieaktywną opcję
                            {
                                <li class="nav-link text-dark">
                                    <span style="color:darkgray">*Admin panel</span>
                                </li>
                            }
                        }

 
                        @* Wylogowanie, Zalogowanie, Zalogowany user *@
                        @if (SignInManager.IsSignedIn(User))
                        {
 
                            <li class="nav-link text-dark">
                                @*<a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Witaj @User.Identity.Name</a>*@
                                Witaj @User.Identity.Name
                            </li>
                            <li class="nav-link text-dark">
                                <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Log out</a>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - YarnShop.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>